[build]
builder = "heroku/buildpacks:20"
buildCommand = "./gradlew build -x test"

[deploy]
startCommand = "java -jar build/libs/*.jar --server.port=$PORT"
healthcheckPath = "/api/todos"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10